---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: pdns-recursor.yml
  when: powerdns_use_recursor

- include: pdns-authoritative.yml
  when: powerdns_use_authoritative
